code

equ	trap_Error								-1
equ	trap_Print								-2
equ	trap_Milliseconds						-3
equ	trap_Cvar_Set							-4
equ	trap_Cvar_SetValue						-5
equ	trap_Cvar_VariableValue					-6
equ	trap_Cvar_VariableIntegerValue			-7
equ	trap_Cvar_VariableStringBuffer			-8
equ	trap_Cvar_Reset							-9
equ	trap_Cvar_Create						-10
equ	trap_Cvar_InfoStringBuffer				-11
equ	trap_Argc								-12
equ	trap_Argv								-13
equ	trap_AddCommand							-14
equ	trap_RemoveCommand						-15
equ	trap_Cmd_ExecuteText					-16
equ	trap_FS_FOpenFile						-17
equ	trap_FS_Read							-18
equ	trap_FS_Write							-19
equ	trap_FS_FCloseFile						-20
equ	trap_FS_GetFileList						-21
equ	trap_R_RegisterModel					-22
equ	trap_R_RegisterSkin						-23
equ	trap_R_RegisterShaderNoMip				-24
equ	trap_R_ClearScene						-25
equ	trap_R_AddRefEntityToScene				-26
equ	trap_R_AddPolyToScene					-27
equ	trap_R_AddLightToScene					-28
equ	trap_R_RenderScene						-29
equ	trap_R_SetColor							-30
equ	trap_R_SetClipRegion					-31
equ	trap_R_DrawStretchPic					-32
equ	trap_UpdateScreen						-33
equ	trap_CM_LerpTag							-34
equ	trap_CM_LoadModel						-35
equ	trap_S_RegisterSound					-36
equ	trap_S_StartLocalSound					-37
equ	trap_Key_KeynumToStringBuf				-38
equ	trap_Key_GetBindingBuf					-39
equ	trap_Key_SetBinding						-40
equ	trap_Key_IsDown							-41
equ	trap_Key_GetOverstrikeMode				-42
equ	trap_Key_SetOverstrikeMode				-43
equ	trap_Key_ClearStates					-44
equ	trap_Key_GetCatcher						-45
equ	trap_Key_SetCatcher						-46
equ	trap_GetClipboardData					-47
equ	trap_GetGlconfig						-48
equ	trap_GetClientState						-49
equ	trap_GetConfigString					-50
equ	trap_LAN_GetPingQueueCount				-51
equ	trap_LAN_ClearPing						-52
equ	trap_LAN_GetPing						-53
equ	trap_LAN_GetPingInfo					-54
equ	trap_Cvar_Register						-55
equ trap_Cvar_Update						-56
equ trap_MemoryRemaining					-57
equ trap_R_RegisterFont						-58
equ trap_R_ModelBounds						-59
equ trap_PC_AddGlobalDefine					-60
equ	trap_PC_LoadSource						-61
equ trap_PC_FreeSource						-62
equ trap_PC_ReadToken						-63
equ trap_PC_SourceFileAndLine				-64
equ trap_S_StopBackgroundTrack				-65
equ trap_S_StartBackgroundTrack				-66
equ trap_RealTime							-67
equ trap_LAN_GetServerCount					-68
equ trap_LAN_GetServerAddressString			-69
equ trap_LAN_GetServerInfo					-70
equ trap_LAN_MarkServerVisible 				-71
equ trap_LAN_UpdateVisiblePings				-72
equ trap_LAN_ResetPings						-73
equ trap_LAN_LoadCachedServers				-74
equ trap_LAN_SaveCachedServers				-75
equ trap_LAN_AddServer						-76
equ trap_LAN_RemoveServer	 				-77
equ trap_CIN_PlayCinematic					-78
equ trap_CIN_StopCinematic					-79
equ trap_CIN_RunCinematic 					-80
equ trap_CIN_DrawCinematic					-81
equ trap_CIN_SetExtents						-82
equ trap_R_RemapShader						-83
equ trap_LAN_ServerStatus					-84
equ trap_LAN_GetServerPing					-85
equ trap_LAN_ServerIsVisible				-86
equ trap_LAN_CompareServers					-87
equ trap_FS_Seek							-88

equ	memset						-101
equ	memcpy						-102
equ	strncpy						-103
equ	sin							-104
equ	cos							-105
equ	atan2						-106
equ	sqrt						-107
equ floor						-108
equ	ceil						-109

