code

equ	trap_Print							-1
equ	trap_Error							-2
equ	trap_Milliseconds					-3
equ	trap_Cvar_Register					-4
equ	trap_Cvar_Update					-5
equ	trap_Cvar_Set						-6
equ trap_Cvar_SetValue					-7
equ trap_Cvar_VariableValue				-8
equ trap_Cvar_VariableStringBuffer		-9
equ	trap_Argc							-10
equ	trap_Argv							-11
equ	trap_Args							-12
equ	trap_FS_FOpenFile					-13
equ	trap_FS_Read						-14
equ	trap_FS_Write						-15
equ	trap_FS_FCloseFile					-16
equ	trap_Cmd_ExecuteText				-17
equ	trap_AddCommand						-18
equ	trap_SendClientCommand				-19
equ	trap_UpdateScreen					-20
equ	trap_CM_LoadMap						-21
equ	trap_CM_NumInlineModels				-22
equ	trap_CM_InlineModel					-23
equ	trap_CM_LoadModel					-24
equ	trap_CM_TempBoxModel				-25
equ	trap_CM_PointContents				-26
equ	trap_CM_TransformedPointContents	-27
equ	trap_CM_BoxTrace					-28
equ	trap_CM_TransformedBoxTrace			-29
equ	trap_CM_MarkFragments				-30
equ	trap_S_StartSound					-31
equ	trap_S_StartLocalSound				-32
equ	trap_S_ClearLoopingSounds			-33
equ	trap_S_AddLoopingSound				-34
equ	trap_S_UpdateEntityPosition			-35
equ	trap_S_Respatialize					-36
equ	trap_S_RegisterSound				-37
equ	trap_S_StartBackgroundTrack			-38
equ	trap_R_LoadWorldMap					-39
equ	trap_R_RegisterModel				-40
equ	trap_R_RegisterSkin					-41
equ	trap_R_RegisterShader				-42
equ	trap_R_ClearScene					-43
equ	trap_R_AddRefEntityToScene			-44
equ	trap_R_AddPolyToScene				-45
equ	trap_R_AddLightToScene				-46
equ	trap_R_RenderScene					-47
equ	trap_R_SetColor						-48
equ	trap_R_DrawStretchPic				-49
equ	trap_R_ModelBounds					-50
equ	trap_R_LerpTag						-51
equ	trap_GetGlconfig					-52
equ	trap_GetGameState					-53
equ	trap_GetCurrentSnapshotNumber		-54
equ	trap_GetSnapshot					-55
equ	trap_GetServerCommand				-56
equ	trap_GetCurrentCmdNumber			-57
equ	trap_GetUserCmd						-58
equ	trap_SetUserCmdValue				-59
equ	trap_R_RegisterShaderNoMip			-60
equ	trap_MemoryRemaining				-61
equ trap_R_RegisterFont					-62
equ trap_Key_IsDown						-63
equ trap_Key_GetCatcher					-64
equ trap_Key_SetCatcher					-65
equ trap_Key_GetKey						-66
equ trap_PC_AddGlobalDefine				-67
equ	trap_PC_LoadSource					-68
equ trap_PC_FreeSource					-69
equ trap_PC_ReadToken					-70
equ trap_PC_SourceFileAndLine			-71
equ trap_S_StopBackgroundTrack			-72
equ trap_RealTime						-73
equ trap_SnapVector						-74
equ trap_RemoveCommand					-75
equ trap_R_LightForPoint				-76
equ trap_CIN_PlayCinematic				-77
equ trap_CIN_StopCinematic				-78
equ trap_CIN_RunCinematic 				-79
equ trap_CIN_DrawCinematic				-80
equ trap_CIN_SetExtents					-81
equ trap_R_RemapShader					-82
equ trap_R_SetClipRegion				-83
equ	trap_S_AddRealLoopingSound			-84
equ trap_S_StopLoopingSound				-85
equ trap_CM_TempCapsuleModel			-86
equ trap_CM_CapsuleTrace				-87
equ trap_CM_TransformedCapsuleTrace		-88
equ trap_R_AddAdditiveLightToScene		-89
equ trap_GetEntityToken					-90
equ	trap_R_AddPolysToScene				-91
equ trap_R_inPVS						-92
equ trap_FS_Seek			-93

equ	memset						-101
equ	memcpy						-102
equ	strncpy						-103
equ	sin							-104
equ	cos							-105
equ	atan2						-106
equ	sqrt						-107
equ floor						-108
equ	ceil						-109
equ	testPrintInt				-110
equ	testPrintFloat				-111
equ acos						-112

